require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe EgivingsController do

  # This should return the minimal set of attributes required to create a valid
  # Egiving. As you add validations to Egiving, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "amount" => "1" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # EgivingsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all egivings as @egivings" do
      egiving = Egiving.create! valid_attributes
      get :index, {}, valid_session
      assigns(:egivings).should eq([egiving])
    end
  end

  describe "GET show" do
    it "assigns the requested egiving as @egiving" do
      egiving = Egiving.create! valid_attributes
      get :show, {:id => egiving.to_param}, valid_session
      assigns(:egiving).should eq(egiving)
    end
  end

  describe "GET new" do
    it "assigns a new egiving as @egiving" do
      get :new, {}, valid_session
      assigns(:egiving).should be_a_new(Egiving)
    end
  end

  describe "GET edit" do
    it "assigns the requested egiving as @egiving" do
      egiving = Egiving.create! valid_attributes
      get :edit, {:id => egiving.to_param}, valid_session
      assigns(:egiving).should eq(egiving)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Egiving" do
        expect {
          post :create, {:egiving => valid_attributes}, valid_session
        }.to change(Egiving, :count).by(1)
      end

      it "assigns a newly created egiving as @egiving" do
        post :create, {:egiving => valid_attributes}, valid_session
        assigns(:egiving).should be_a(Egiving)
        assigns(:egiving).should be_persisted
      end

      it "redirects to the created egiving" do
        post :create, {:egiving => valid_attributes}, valid_session
        response.should redirect_to(Egiving.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved egiving as @egiving" do
        # Trigger the behavior that occurs when invalid params are submitted
        Egiving.any_instance.stub(:save).and_return(false)
        post :create, {:egiving => { "amount" => "invalid value" }}, valid_session
        assigns(:egiving).should be_a_new(Egiving)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Egiving.any_instance.stub(:save).and_return(false)
        post :create, {:egiving => { "amount" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested egiving" do
        egiving = Egiving.create! valid_attributes
        # Assuming there are no other egivings in the database, this
        # specifies that the Egiving created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Egiving.any_instance.should_receive(:update_attributes).with({ "amount" => "1" })
        put :update, {:id => egiving.to_param, :egiving => { "amount" => "1" }}, valid_session
      end

      it "assigns the requested egiving as @egiving" do
        egiving = Egiving.create! valid_attributes
        put :update, {:id => egiving.to_param, :egiving => valid_attributes}, valid_session
        assigns(:egiving).should eq(egiving)
      end

      it "redirects to the egiving" do
        egiving = Egiving.create! valid_attributes
        put :update, {:id => egiving.to_param, :egiving => valid_attributes}, valid_session
        response.should redirect_to(egiving)
      end
    end

    describe "with invalid params" do
      it "assigns the egiving as @egiving" do
        egiving = Egiving.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Egiving.any_instance.stub(:save).and_return(false)
        put :update, {:id => egiving.to_param, :egiving => { "amount" => "invalid value" }}, valid_session
        assigns(:egiving).should eq(egiving)
      end

      it "re-renders the 'edit' template" do
        egiving = Egiving.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Egiving.any_instance.stub(:save).and_return(false)
        put :update, {:id => egiving.to_param, :egiving => { "amount" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested egiving" do
      egiving = Egiving.create! valid_attributes
      expect {
        delete :destroy, {:id => egiving.to_param}, valid_session
      }.to change(Egiving, :count).by(-1)
    end

    it "redirects to the egivings list" do
      egiving = Egiving.create! valid_attributes
      delete :destroy, {:id => egiving.to_param}, valid_session
      response.should redirect_to(egivings_url)
    end
  end

end
