require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe MinistryChildrenController do

  # This should return the minimal set of attributes required to create a valid
  # MinistryChild. As you add validations to MinistryChild, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # MinistryChildrenController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all ministry_children as @ministry_children" do
      ministry_child = MinistryChild.create! valid_attributes
      get :index, {}, valid_session
      assigns(:ministry_children).should eq([ministry_child])
    end
  end

  describe "GET show" do
    it "assigns the requested ministry_child as @ministry_child" do
      ministry_child = MinistryChild.create! valid_attributes
      get :show, {:id => ministry_child.to_param}, valid_session
      assigns(:ministry_child).should eq(ministry_child)
    end
  end

  describe "GET new" do
    it "assigns a new ministry_child as @ministry_child" do
      get :new, {}, valid_session
      assigns(:ministry_child).should be_a_new(MinistryChild)
    end
  end

  describe "GET edit" do
    it "assigns the requested ministry_child as @ministry_child" do
      ministry_child = MinistryChild.create! valid_attributes
      get :edit, {:id => ministry_child.to_param}, valid_session
      assigns(:ministry_child).should eq(ministry_child)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new MinistryChild" do
        expect {
          post :create, {:ministry_child => valid_attributes}, valid_session
        }.to change(MinistryChild, :count).by(1)
      end

      it "assigns a newly created ministry_child as @ministry_child" do
        post :create, {:ministry_child => valid_attributes}, valid_session
        assigns(:ministry_child).should be_a(MinistryChild)
        assigns(:ministry_child).should be_persisted
      end

      it "redirects to the created ministry_child" do
        post :create, {:ministry_child => valid_attributes}, valid_session
        response.should redirect_to(MinistryChild.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved ministry_child as @ministry_child" do
        # Trigger the behavior that occurs when invalid params are submitted
        MinistryChild.any_instance.stub(:save).and_return(false)
        post :create, {:ministry_child => { "name" => "invalid value" }}, valid_session
        assigns(:ministry_child).should be_a_new(MinistryChild)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        MinistryChild.any_instance.stub(:save).and_return(false)
        post :create, {:ministry_child => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested ministry_child" do
        ministry_child = MinistryChild.create! valid_attributes
        # Assuming there are no other ministry_children in the database, this
        # specifies that the MinistryChild created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        MinistryChild.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => ministry_child.to_param, :ministry_child => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested ministry_child as @ministry_child" do
        ministry_child = MinistryChild.create! valid_attributes
        put :update, {:id => ministry_child.to_param, :ministry_child => valid_attributes}, valid_session
        assigns(:ministry_child).should eq(ministry_child)
      end

      it "redirects to the ministry_child" do
        ministry_child = MinistryChild.create! valid_attributes
        put :update, {:id => ministry_child.to_param, :ministry_child => valid_attributes}, valid_session
        response.should redirect_to(ministry_child)
      end
    end

    describe "with invalid params" do
      it "assigns the ministry_child as @ministry_child" do
        ministry_child = MinistryChild.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MinistryChild.any_instance.stub(:save).and_return(false)
        put :update, {:id => ministry_child.to_param, :ministry_child => { "name" => "invalid value" }}, valid_session
        assigns(:ministry_child).should eq(ministry_child)
      end

      it "re-renders the 'edit' template" do
        ministry_child = MinistryChild.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        MinistryChild.any_instance.stub(:save).and_return(false)
        put :update, {:id => ministry_child.to_param, :ministry_child => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested ministry_child" do
      ministry_child = MinistryChild.create! valid_attributes
      expect {
        delete :destroy, {:id => ministry_child.to_param}, valid_session
      }.to change(MinistryChild, :count).by(-1)
    end

    it "redirects to the ministry_children list" do
      ministry_child = MinistryChild.create! valid_attributes
      delete :destroy, {:id => ministry_child.to_param}, valid_session
      response.should redirect_to(ministry_children_url)
    end
  end

end
