require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SermonPicturesController do

  # This should return the minimal set of attributes required to create a valid
  # SermonPicture. As you add validations to SermonPicture, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "sermon_image" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SermonPicturesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sermon_pictures as @sermon_pictures" do
      sermon_picture = SermonPicture.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sermon_pictures).should eq([sermon_picture])
    end
  end

  describe "GET show" do
    it "assigns the requested sermon_picture as @sermon_picture" do
      sermon_picture = SermonPicture.create! valid_attributes
      get :show, {:id => sermon_picture.to_param}, valid_session
      assigns(:sermon_picture).should eq(sermon_picture)
    end
  end

  describe "GET new" do
    it "assigns a new sermon_picture as @sermon_picture" do
      get :new, {}, valid_session
      assigns(:sermon_picture).should be_a_new(SermonPicture)
    end
  end

  describe "GET edit" do
    it "assigns the requested sermon_picture as @sermon_picture" do
      sermon_picture = SermonPicture.create! valid_attributes
      get :edit, {:id => sermon_picture.to_param}, valid_session
      assigns(:sermon_picture).should eq(sermon_picture)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SermonPicture" do
        expect {
          post :create, {:sermon_picture => valid_attributes}, valid_session
        }.to change(SermonPicture, :count).by(1)
      end

      it "assigns a newly created sermon_picture as @sermon_picture" do
        post :create, {:sermon_picture => valid_attributes}, valid_session
        assigns(:sermon_picture).should be_a(SermonPicture)
        assigns(:sermon_picture).should be_persisted
      end

      it "redirects to the created sermon_picture" do
        post :create, {:sermon_picture => valid_attributes}, valid_session
        response.should redirect_to(SermonPicture.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sermon_picture as @sermon_picture" do
        # Trigger the behavior that occurs when invalid params are submitted
        SermonPicture.any_instance.stub(:save).and_return(false)
        post :create, {:sermon_picture => { "sermon_image" => "invalid value" }}, valid_session
        assigns(:sermon_picture).should be_a_new(SermonPicture)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SermonPicture.any_instance.stub(:save).and_return(false)
        post :create, {:sermon_picture => { "sermon_image" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sermon_picture" do
        sermon_picture = SermonPicture.create! valid_attributes
        # Assuming there are no other sermon_pictures in the database, this
        # specifies that the SermonPicture created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SermonPicture.any_instance.should_receive(:update_attributes).with({ "sermon_image" => "MyString" })
        put :update, {:id => sermon_picture.to_param, :sermon_picture => { "sermon_image" => "MyString" }}, valid_session
      end

      it "assigns the requested sermon_picture as @sermon_picture" do
        sermon_picture = SermonPicture.create! valid_attributes
        put :update, {:id => sermon_picture.to_param, :sermon_picture => valid_attributes}, valid_session
        assigns(:sermon_picture).should eq(sermon_picture)
      end

      it "redirects to the sermon_picture" do
        sermon_picture = SermonPicture.create! valid_attributes
        put :update, {:id => sermon_picture.to_param, :sermon_picture => valid_attributes}, valid_session
        response.should redirect_to(sermon_picture)
      end
    end

    describe "with invalid params" do
      it "assigns the sermon_picture as @sermon_picture" do
        sermon_picture = SermonPicture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SermonPicture.any_instance.stub(:save).and_return(false)
        put :update, {:id => sermon_picture.to_param, :sermon_picture => { "sermon_image" => "invalid value" }}, valid_session
        assigns(:sermon_picture).should eq(sermon_picture)
      end

      it "re-renders the 'edit' template" do
        sermon_picture = SermonPicture.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SermonPicture.any_instance.stub(:save).and_return(false)
        put :update, {:id => sermon_picture.to_param, :sermon_picture => { "sermon_image" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sermon_picture" do
      sermon_picture = SermonPicture.create! valid_attributes
      expect {
        delete :destroy, {:id => sermon_picture.to_param}, valid_session
      }.to change(SermonPicture, :count).by(-1)
    end

    it "redirects to the sermon_pictures list" do
      sermon_picture = SermonPicture.create! valid_attributes
      delete :destroy, {:id => sermon_picture.to_param}, valid_session
      response.should redirect_to(sermon_pictures_url)
    end
  end

end
