require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ServiceTimesController do

  # This should return the minimal set of attributes required to create a valid
  # ServiceTime. As you add validations to ServiceTime, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "day" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ServiceTimesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all service_times as @service_times" do
      service_time = ServiceTime.create! valid_attributes
      get :index, {}, valid_session
      assigns(:service_times).should eq([service_time])
    end
  end

  describe "GET show" do
    it "assigns the requested service_time as @service_time" do
      service_time = ServiceTime.create! valid_attributes
      get :show, {:id => service_time.to_param}, valid_session
      assigns(:service_time).should eq(service_time)
    end
  end

  describe "GET new" do
    it "assigns a new service_time as @service_time" do
      get :new, {}, valid_session
      assigns(:service_time).should be_a_new(ServiceTime)
    end
  end

  describe "GET edit" do
    it "assigns the requested service_time as @service_time" do
      service_time = ServiceTime.create! valid_attributes
      get :edit, {:id => service_time.to_param}, valid_session
      assigns(:service_time).should eq(service_time)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ServiceTime" do
        expect {
          post :create, {:service_time => valid_attributes}, valid_session
        }.to change(ServiceTime, :count).by(1)
      end

      it "assigns a newly created service_time as @service_time" do
        post :create, {:service_time => valid_attributes}, valid_session
        assigns(:service_time).should be_a(ServiceTime)
        assigns(:service_time).should be_persisted
      end

      it "redirects to the created service_time" do
        post :create, {:service_time => valid_attributes}, valid_session
        response.should redirect_to(ServiceTime.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved service_time as @service_time" do
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceTime.any_instance.stub(:save).and_return(false)
        post :create, {:service_time => { "day" => "invalid value" }}, valid_session
        assigns(:service_time).should be_a_new(ServiceTime)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceTime.any_instance.stub(:save).and_return(false)
        post :create, {:service_time => { "day" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested service_time" do
        service_time = ServiceTime.create! valid_attributes
        # Assuming there are no other service_times in the database, this
        # specifies that the ServiceTime created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ServiceTime.any_instance.should_receive(:update_attributes).with({ "day" => "MyString" })
        put :update, {:id => service_time.to_param, :service_time => { "day" => "MyString" }}, valid_session
      end

      it "assigns the requested service_time as @service_time" do
        service_time = ServiceTime.create! valid_attributes
        put :update, {:id => service_time.to_param, :service_time => valid_attributes}, valid_session
        assigns(:service_time).should eq(service_time)
      end

      it "redirects to the service_time" do
        service_time = ServiceTime.create! valid_attributes
        put :update, {:id => service_time.to_param, :service_time => valid_attributes}, valid_session
        response.should redirect_to(service_time)
      end
    end

    describe "with invalid params" do
      it "assigns the service_time as @service_time" do
        service_time = ServiceTime.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceTime.any_instance.stub(:save).and_return(false)
        put :update, {:id => service_time.to_param, :service_time => { "day" => "invalid value" }}, valid_session
        assigns(:service_time).should eq(service_time)
      end

      it "re-renders the 'edit' template" do
        service_time = ServiceTime.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ServiceTime.any_instance.stub(:save).and_return(false)
        put :update, {:id => service_time.to_param, :service_time => { "day" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested service_time" do
      service_time = ServiceTime.create! valid_attributes
      expect {
        delete :destroy, {:id => service_time.to_param}, valid_session
      }.to change(ServiceTime, :count).by(-1)
    end

    it "redirects to the service_times list" do
      service_time = ServiceTime.create! valid_attributes
      delete :destroy, {:id => service_time.to_param}, valid_session
      response.should redirect_to(service_times_url)
    end
  end

end
